{{- if eq .Values.global.cloudProvider "aws" }}
apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  targetReference:
    name: {{ .Release.Name }}
  defaultConfiguration:
    targetType: ip
    healthCheckConfig:
      healthCheckPath: /kiali        # not "/" — see below
      matcher:
        httpCode: 200-499
{{- end }}
