global:
  prefix: "{{ .config.prefix }}"
  internalGateway: "{{ .module.name }}-internal"
  externalGateway: "{{ .module.name }}-external"
gateways:
  external:
    certificateMap: "{{ .toutput.dns.pub_zone_id }}"
    sslPolicy: "{{ .toptout.dns.ssl_policy_modern }}"
  internal:
    certManagerCerts: "{{ .toutput.dns.int_zone_id }}"
    sslPolicy: "{{ .toptout.dns.ssl_policy_modern }}"
