global:
  bucketName: "{{ .config.prefix }}-{{ .module.name }}-metrics"
  google:
    projectID: "{{ .toutput.crossplane.project_id }}"
    bucket:
      location: "{{ .toutput.gke.region }}"
      kmsKeyId: "{{ .toptout.kms.telemetry_key_id }}"
