{{- if eq .Values.global.cloudProvider "google" }}

apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
  name: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: '-2'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  forProvider:
    member: serviceAccount:{{ .Values.global.google.projectID }}.svc.id.goog[{{ .Release.Name }}/{{ (index .Values "external-dns" "serviceAccount" "name") }}]
    project: {{ .Values.global.google.projectID }}
    role: roles/dns.admin
  providerConfigRef:
    name: {{ .Values.global.providerConfigRefName }}

{{- end }}
