global:
  datasources:
    loki:
      hostname: "http://{{ .tmodule.loki }}-gateway.{{ .tmodule.loki }}"
    prometheus:
      hostname: "http://{{ .tmodule.prometheus }}-server.{{ .tmodule.prometheus }}"

grafana:
  grafana.ini:
    server:
      root_url: https://{{ .module.name }}.{{ .toptout.route53.int_domain | .toptout.dns.int_domain | required }}
    users:
      home_page: "https://{{ .module.name }}.{{ .toptout.route53.int_domain | .toptout.dns.int_domain | required }}/dashboards"

  route:
    main:
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: '{{ .toptin.aws-alb.global.internalGateway | .toptin.google-gateway.global.internalGateway | required }}'
          namespace: '{{ .toptmodule.aws-alb | .toptmodule.google-gateway | required }}'
          sectionName: https
      hostnames:
        - "{{ .module.name }}.{{ .toptout.route53.int_domain | .toptout.dns.int_domain | required }}"
  image:
    registry: '{{ .toptout.ecr-proxy.hub_registry | .toptout.gar-proxy.hub_registry | "docker.io" }}'
  sidecar:
    image:
      registry: '{{ .toptout.ecr-proxy.quay_registry | .toptout.gar-proxy.quay_registry | "quay.io" }}'
  initChownData:
    image:
      registry: '{{ .toptout.ecr-proxy.hub_registry | .toptout.gar-proxy.hub_registry | "docker.io" }}'
  downloadDashboardsImage:
    registry: '{{ .toptout.ecr-proxy.hub_registry | .toptout.gar-proxy.hub_registry | "docker.io" }}'
  imageRenderer:
    image:
      registry: '{{ .toptout.ecr-proxy.hub_registry | .toptout.gar-proxy.hub_registry | "docker.io" }}'
