global:
  aws:
    account: "{{ .toutput.eks.account }}"
    clusterOIDC: "{{ .toutput.eks.oidc_provider }}"
    region: "{{ .toutput.eks.region }}"
  datasources:
    loki:
      hostname: "http://{{ .tmodule.loki }}-gateway.{{ .tmodule.loki }}"
    prometheus:
      hostname: "http://{{ .tmodule.prometheus }}-server.{{ .tmodule.prometheus }}"

grafana:
  grafana.ini:
    server:
      root_url: https://{{ .module.name }}.{{ .toutput.route53.int_domain }}
    users:
      home_page: "https://{{ .module.name }}.{{ .toutput.route53.int_domain }}/dashboards"
  ingress:
    enabled: "{{ .tinput.aws-alb.global.createIngress }}"
    hosts:
      - "{{ .module.name }}.{{ .toutput.route53.int_domain }}"
  route:
    main:
      enabled: "{{ .tinput.aws-alb.global.createRoute }}"
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: "{{ .tinput.aws-alb.global.internalGateway }}"
          namespace: "{{ .tmodule.aws-alb }}"
          sectionName: https
      hostnames:
        - "{{ .module.name }}.{{ .toutput.route53.int_domain }}"
