global:
  cloudProvider: "google"
  providerConfigRefName: "crossplane-google"

  google:
    projectID: ""

grafana:
  ingress:
    enabled: false
  route:
    main:
      # google has no ingress, the gateway route is always on
      enabled: true
  persistence:
    storageClassName: "standard"
