gateways:
  external:
    certificateOcid: "{{ .toutput.dns.pub_cert_ocid }}"
    domain: "{{ .toutput.dns.pub_domain }}"
  internal:
    certificateOcid: "{{ .toutput.dns.int_cert_ocid }}"
    domain: "{{ .toutput.dns.int_domain }}"
