{{ if not (eq .Values.global.gitlab.url "") }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gitlab-secret-store
spec:
  provider:
    # provider type: gitlab
    gitlab:
      url: {{ .Values.global.gitlab.url }}
      auth:
        SecretRef:
          accessToken:
            namespace: {{ .Release.Namespace }}
            name: gitlab-secret
            key: token
      projectID: "{{ .Values.global.gitlab.project }}"
{{ end }}
