global:
  aws:
    account: "{{ .toutput.eks.account }}"
    clusterOIDC: "{{ .toutput.eks.oidc_provider }}"
    region: "{{ .toutput.eks.region }}"
    kmsKeyId: "{{ .toptout.kms.telemetry_alias_arn }}"
    publicSubnetCidrs: "{{ .toutput.vpc.public_subnets_cidr_blocks }}"
    privateSubnetCidrs: "{{ .toutput.vpc.private_subnets_cidr_blocks }}"
    serviceSubnetCidrs: "{{ .toutput.vpc.service_subnets_cidr_blocks }}"
  bucketName: "{{ .config.prefix }}-{{ .module.name }}-{{ .toutput.eks.account }}-{{ .toutput.eks.region }}"
loki:
  gateway:
    ingress:
      enabled: "{{ .tinput.aws-alb.global.createIngress }}"
      hosts:
        - host: "{{ .module.name }}.{{ .toutput.route53.int_domain }}"
          paths:
            - path: "/"
              pathType: "Prefix"
    route:
      main:
        enabled: "{{ .tinput.aws-alb.global.createRoute }}"
        # Pin to avoid Capabilities auto-detect under ArgoCD repo-server discovery cache
        apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: "{{ .tinput.aws-alb.global.internalGateway }}"
          namespace: "{{ .tmodule.aws-alb }}"
          sectionName: https
        hostnames:
          - "{{ .module.name }}.{{ .toutput.route53.int_domain }}"
  loki:
    storage:
      s3:
        region: "{{ .toutput.eks.region }}"
      bucketNames:
        chunks: "{{ .config.prefix }}-{{ .module.name }}-{{ .toutput.eks.account }}-{{ .toutput.eks.region }}"
        ruler: "{{ .config.prefix }}-{{ .module.name }}-{{ .toutput.eks.account }}-{{ .toutput.eks.region }}"
        admin: "{{ .config.prefix }}-{{ .module.name }}-{{ .toutput.eks.account }}-{{ .toutput.eks.region }}"
    structuredConfig:
      storage_config:
        aws:
          region: "{{ .toutput.eks.region }}"
          bucketnames: "{{ .config.prefix }}-{{ .module.name }}-{{ .toutput.eks.account }}-{{ .toutput.eks.region }}"
  networkPolicy:
    externalStorage:
     cidrs:
     - "0.0.0.0/0"
    ingress:
        namespaceSelector:
          matchExpressions:
            - key: kubernetes.io/metadata.name
              operator: Exists
        podSelector:
            matchExpressions:
            - key: netpol-loki
              operator: In
              values:
              - 'loki'
              - '{{ .module.name }}'

