global:
  bucketName: "{{ .config.prefix }}-{{ .module.name }}-logs"
  google:
    projectID: "{{ .toutput.crossplane.project_id }}"
    publicSubnetCidrs: "{{.toutput.vpc.public_subnet_cidrs}}"
    bucket:
      location: "{{ .toutput.gke.region }}"
      kmsKeyId: "{{ .toptout.kms.telemetry_key_id }}"
loki:
  loki:
    storage:
      bucketNames:
        admin: "{{ .config.prefix }}-{{ .module.name }}-logs"
        chunks: "{{ .config.prefix }}-{{ .module.name }}-logs"
        ruler: "{{ .config.prefix }}-{{ .module.name }}-logs"
  networkPolicy:
    externalStorage:
      cidrs:
        - "0.0.0.0/0"
    ingress:
      namespaceSelector:
        matchExpressions:
          - key: kubernetes.io/metadata.name
            operator: Exists
      podSelector:
        matchExpressions:
          - key: netpol-loki
            operator: In
            values:
              - "loki"
              - "{{ .module.name }}"
