{{- if eq .Values.global.cloudProvider "google" }}

apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountIAMMember
metadata:
  name: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  forProvider:
    member: "serviceAccount:{{ .Values.global.google.projectID }}.svc.id.goog[{{ .Release.Namespace }}/{{ .Values.grafana.serviceAccount.name }}]"
    role: roles/iam.workloadIdentityUser
    serviceAccountIdRef:
      name: {{ .Values.grafana.serviceAccount.name }}
  providerConfigRef:
    name: {{ .Values.global.providerConfigRefName }}

{{- end }}
