
image: 
  registry: '{{ .toptout.ecr-proxy.hub_registry | "docker.io" }}/entigolabs/saml-proxy'
secretStore:
  name: "{{ .tmodule.external-secrets }}"

global:
  hostname: "{{ .module.name }}.{{ .toutput.route53.pub_domain }}"
  createRoute: "{{ .tinput.aws-alb.global.createRoute }}"
  gateway:
    name: "{{ .tinput.aws-alb.global.externalGateway }}"
    namespace: "{{ .tmodule.aws-alb }}"
  aws:
    createIngress: "{{ .tinput.aws-alb.global.createIngress }}"
