prometheus:
  server:
    route:
      main:
        enabled: "{{ .tinput.aws-alb.global.createRoute }}"
    ingress:
      enabled: "{{ .tinput.aws-alb.global.createIngress }}"
      hosts:
        - "{{ .module.name }}.{{ .toutput.route53.int_domain }}"
