apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-delete-default-mrap
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-delete-default-mrap
rules:
- apiGroups: ["apiextensions.crossplane.io"]
  resources: ["managedresourceactivationpolicies"]
  resourceNames: ["default"]
  verbs: ["get", "delete", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-delete-default-mrap
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-delete-default-mrap
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-delete-default-mrap
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-delete-default-mrap
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    kube-score/ignore: pod-networkpolicy
spec:
  activeDeadlineSeconds: 600
  parallelism: 1
  completions: 1
  template:
    spec:
      serviceAccountName: {{ .Release.Name }}-delete-default-mrap
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            preference:
              matchExpressions:
              - key: tools
                operator: In
                values:
                - "true"
      tolerations:
        - key: "tools"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
      - name: kubectl
        image: {{ .Values.job.image }}:{{ .Values.job.tag }}
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
            ephemeral-storage: 200Mi
          requests:
            cpu: 1m
            memory: 16Mi
            ephemeral-storage: 2Mi
        command:
        - /bin/bash
        - -c
        - |
          # Delete the default managedresourceactivationpolicies.
          kubectl delete managedresourceactivationpolicies.apiextensions.crossplane.io default || true
      restartPolicy: Never
  backoffLimit: 5
