{{- if and (eq .Values.global.cloudProvider "aws") .Values.global.createClusterSecretStore }}

apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  name: {{ .Release.Name }}  
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    crossplane.io/external-name: "{{ .Release.Name }}"
spec:
  forProvider:
    tags:
      created-by: "entigo-infralib"
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
{{- if .Values.global.enableWriteForClusterSecretStore }}
              "secretsmanager:ListSecrets",
              "secretsmanager:CreateSecret",
              "secretsmanager:DeleteSecret",
              "secretsmanager:TagResource",
{{- end }}
              "secretsmanager:GetResourcePolicy",
              "secretsmanager:GetSecretValue",
              "secretsmanager:DescribeSecret",
              "secretsmanager:ListSecretVersionIds"
            ],
            "Resource": [
              "arn:aws:secretsmanager:{{ .Values.global.aws.region }}:{{ .Values.global.aws.account }}:secret:*"
            ]
          }
        ]
      }

  providerConfigRef:
    name: {{ .Values.global.providerConfigRefName }}

{{- end }}
