{{- if and (eq .Values.global.cloudProvider "aws") .Values.global.createClusterSecretStore }}

apiVersion: iam.aws.crossplane.io/v1beta1
kind: Role
metadata:
  name: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  managementPolicies: ["Observe"]
  deletionPolicy: Orphan
  forProvider:
    tags:
      - key: created-by
        value: entigo-infralib
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Federated": "arn:aws:iam::{{ .Values.global.aws.account }}:oidc-provider/{{ .Values.global.aws.clusterOIDC }}"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
              "StringEquals": {
                "{{ .Values.global.aws.clusterOIDC }}:aud": "sts.amazonaws.com",
                "{{ .Values.global.aws.clusterOIDC }}:sub": "system:serviceaccount:{{ .Release.Namespace }}:secret-manager-operator"
              }
            }
          }
        ]
      }
  providerConfigRef:
    name: {{ .Values.global.providerConfigRefName }}
    
{{- end }}
