global:
  cloudProvider: aws
  providerConfigRefName: crossplane-aws

  aws:
    account: ""
    clusterOIDC: ""
    assumeRole: ""

external-dns:
  provider:
    name: aws
  env:
    - name: AWS_DEFAULT_REGION
      value: ""
  serviceAccount:
    create: false
