wireguard:
  service:
    annotations:
      # The NLB terminates TLS for the pubkey port declared in values-aws.yaml
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "{{ .toutput.route53.pub_cert_arn }}"
