global:
  # Own hostname, because the wireguard load balancer cannot serve this
  # endpoint on google. See README.md.
  pubkeyHostname: "{{ .module.name }}-pubkey.{{ .toutput.dns.pub_domain }}"
  gateway:
    name: "{{ .tinput.google-gateway.global.externalGateway }}"
    namespace: "{{ .tmodule.google-gateway }}"
