regions:
- eu-frankfurt-2

accounts:
  ocid1.compartment.oc19..aaaaaaaavzlzuvoosubz3nz5f727qiidbicp5myfmoieb4xqthszyful262q:
    filters:
      OCICustomerSecretKey:
      - property: Name
        type: In
        values:
        - entigo-infralib-biz-state
        - entigo-infralib-pri-state
      OCIUser:
      - property: Name
        type: In
        values:
        - biz-loki
        - biz-mimir
      OCIGroup:
      - property: Name
        type: In
        values:
        - biz-loki
        - biz-mimir
      OCIPolicy:
      - property: Name
        type: In
        values:
        - infralib-agent-bootstrap
        - infralib-github-bootstrap
      OCIVault:
      - property: Name
        type: In
        values:
        - biz-eu-frankfurt-2
        - at-eu-frankfurt-2
        - pri-eu-frankfurt-2
      OCIKey:
      - property: Name
        type: In
        values:
        - biz-eu-frankfurt-2-agent
        - at-eu-frankfurt-2-agent
        - pri-eu-frankfurt-2-agent
        - biz-net-pca-ca
        - at-net-pca-ca
        - pri-net-pca-ca
      OCICertificateAuthority:
      - property: Name
        type: In
        values:
        - biz-net-pca-root-ca
        - pri-net-pca-root-ca
