regions:
- eu-frankfurt-1

accounts:
  ocid1.compartment.oc1..aaaaaaaa4s6svm4opv5vovkdccgs72xlkmfab25tmblrszb6weyk6qpt255q:
    filters:
      OCIDnsZone:
      - property: Name
        type: In
        values:
        - oci.infralib.entigo.io
      OCIUser:
      - property: Name
        type: In
        values:
        - biz-loki
        - biz-mimir
      OCIGroup:
      - property: Name
        type: In
        values:
        - biz-loki
        - biz-mimir
      OCIPolicy:
      - property: Name
        type: In
        values:
        - infralib-agent-bootstrap
      OCIVault:
      - property: Name
        type: In
        values:
        - biz-eu-frankfurt-1
        - at-eu-frankfurt-1
        - pri-eu-frankfurt-1
      OCIKey:
      - property: Name
        type: In
        values:
        - biz-eu-frankfurt-1-agent
        - at-eu-frankfurt-1-agent
        - pri-eu-frankfurt-1-agent
        - biz-net-pca-ca
        - at-net-pca-ca
        - pri-net-pca-ca
      OCICertificateAuthority:
      - property: Name
        type: In
        values:
        - biz-net-pca-root-ca-3pbbwkcu
        - pri-net-pca-root-ca
