{{- if eq .Values.global.cloudProvider "google" }}

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-gke-metadata
  namespace: {{ .Release.Name }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    # GKE Dataplane V1
    - to:
        - ipBlock:
            cidr: 169.254.169.252/32
      ports:
        - protocol: TCP
          port: 988
    # GKE Dataplane V2
    - to:
        - ipBlock:
            cidr: 169.254.169.254/32
      ports:
        - protocol: TCP
          port: 80

{{- if .Values.global.google.gateway.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-gateway-health-check
  namespace: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: gateway
  policyTypes:
    - Ingress
  ingress:
    - from:
        # https://docs.cloud.google.com/load-balancing/docs/health-check-concepts#ip-ranges
        - ipBlock:
            cidr: 35.191.0.0/16
        - ipBlock:
            cidr: 130.211.0.0/22
        {{- range (splitList "," (.Values.global.google.publicSubnetCidrs | default "")) }}
        {{- if trim . }}
        - ipBlock:
            cidr: {{ trim . }}
        {{- end }}
        {{- end }}
        {{- range .Values.global.google.gateway.extraHealthCheckCidrs }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}
      ports:
        - protocol: TCP
          port: http
{{- end }}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-grafana
  namespace: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: gateway
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              app.kubernetes.io/name: grafana
      ports:
        - protocol: TCP
          port: http

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-alloy
  namespace: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: gateway
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              app.kubernetes.io/name: logs
      ports:
        - protocol: TCP
          port: http

{{- end }}
