{{- if .Values.installCompositeResources }}
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: cronjobs.workload.entigo.com
spec:
  compositeTypeRef:
    apiVersion: workload.entigo.com/v1alpha1
    kind: CronJob
  mode: Pipeline
  pipeline:
    - step: cron-job
      functionRef:
        name: developer-portal-function
{{- end }}
