{{- if .Values.installCompositeResources }}
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: entigorepositories.artifacts.entigo.com
spec:
  compositeTypeRef:
    apiVersion: artifacts.entigo.com/v1alpha1
    kind: EntigoRepository
  mode: Pipeline
  pipeline:
    - step: repository
      functionRef:
        name: developer-portal-function
{{- end }}
