{{- if .Values.installCompositeResources }}
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: webaccesses.network.entigo.com
spec:
  compositeTypeRef:
    apiVersion: network.entigo.com/v1alpha1
    kind: WebAccess
  mode: Pipeline
  pipeline:
    - step: web-access
      functionRef:
        name: developer-portal-function
{{- end }}
