apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-loki
  namespace: {{ .Release.Namespace }}
spec:
  egress:
    - ports:
        - port: 8080
          protocol: TCP
        - port: 80
          protocol: TCP
      to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              app.kubernetes.io/name: loki
              app.kubernetes.io/component: gateway
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: promtail
  policyTypes:
    - Egress
