global:
  google:
    projectID: "{{ .toutput.crossplane.project_id }}"
    bucket:
      location: "{{ .toutput.gke.region }}"
      kmsKeyId: "{{ .toptout.kms.data_key_id }}"
harbor:
  persistence:
    imageChartStorage:
      gcs:
        bucket: "{{ .config.prefix }}-{{ .module.name }}"
