global:
  cloudProvider: google
  providerConfigRefName: crossplane-google

  google:
    projectID: ""
    bucket:
      location: ""
      kmsKeyId: ""

harbor:
  expose:
    # google has no ingress, the gateway route is always on
    type: route
    tls:
      enabled: false
  persistence:
    imageChartStorage:
      type: gcs
      gcs:
        useWorkloadIdentity: true
        bucket: ""
  registry:
    serviceAccountName: harbor
    automountServiceAccountToken: true
