global:
  cloudProvider: ""
  providerConfigRefName: ""

resources:
  limits:
    cpu: 1
    memory: 1204Mi
    ephemeral-storage: 1Gi
  requests:
    cpu: 10m
    memory: 64Mi
    ephemeral-storage: 10Mi

installCompositeResources: true
config: {}

image:
  repository: docker.io/entigolabs/developer-portal-agent
  tag: main-62

function:
  repository: docker.io/entigolabs/developer-portal-function
  tag: v0.0.0-20250822123128-6dc1a5b95889

tolerations:
  - key: "tools"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 90
        preference:
          matchExpressions:
            - key: tools
              operator: In
              values:
                - "true"
