crossplane:
  serviceAccount:
    customAnnotations: 
      eks.amazonaws.com/role-arn: "{{ .toutput.crossplane.iam_role_core }}"

global:
  aws:
    region: "{{ .toutput.eks.region }}"
    ecrPolicy: "{{ .toptout.ecr-proxy.policy }}"


