global:
  cloudProvider: "aws"
  aws:
    region: ""
    ecrRole: ""
    ecrPolicy: ""

crossplane:
  resourcesCrossplane:
    limits:
      # -- CPU resource limits for Crossplane.
      cpu: 2000m
      # -- Memory resource limits for Crossplane.
      memory: 1536Mi
    requests:
      # -- CPU resource requests for Crossplane.
      cpu: 30m
      # -- Memory resource requests for Crossplane.
      memory: 450Mi
