{{- if eq .Values.global.cloudProvider "aws" }}
apiVersion: iam.aws.crossplane.io/v1beta1
kind: Policy
metadata:
  name: {{ .Release.Name }}
spec:
  forProvider:
    name: {{ .Release.Name }}
    tags:
      - key: created-by
        value: entigo-infralib
    document: |
      {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Effect": "Allow",
                  "Action": [
                      "sts:GetCallerIdentity"
                  ],
                  "Resource": "*"
              }
          ]
      }
  providerConfigRef:
    name: {{ .Values.global.providerConfigRefName }}

{{- end }}
