{{- if eq .Values.global.cloudProvider "aws" }}
apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  name: {{ .Release.Name }}
  annotations:
    crossplane.io/external-name: "{{ .Release.Name }}"
    argocd.argoproj.io/sync-wave: '-2'
spec:
  forProvider:
    tags:
      created-by: "entigo-infralib"
    policy: |
      {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Effect": "Allow",
                  "Action": [
                      "sts:GetCallerIdentity"
                  ],
                  "Resource": "*"
              }
          ]
      }
  providerConfigRef:
    name: {{ .Values.global.providerConfigRefName }}

{{- end }}
