{{- if and 
    (eq .Values.global.cloudProvider "google")
    (not (empty .Values.global.google.createGARProjects))
    (.Values.global.google.createGARNamespace)
}}
{{- $gsa := printf "%s-gar" .Release.Name }}
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  name: {{ $gsa }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  forProvider:
    displayName: Artifact Registry token service account
  providerConfigRef:
    name: {{ .Values.global.providerConfigRefName }}
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountIAMMember
metadata:
  name: {{ .Release.Name }}-gar-token
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  forProvider:
    member: serviceAccount:{{ .Values.global.google.projectID }}.svc.id.goog[{{ .Values.global.google.createGARNamespace }}/gar-token]
    role: roles/iam.workloadIdentityUser
    serviceAccountIdRef:
      name: {{ $gsa }}
  providerConfigRef:
    name: {{ .Values.global.providerConfigRefName }}
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
  name: {{ .Release.Name }}-gar-token
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  forProvider:
    member: serviceAccount:{{ $gsa }}@{{ .Values.global.google.projectID }}.iam.gserviceaccount.com
    project: {{ .Values.global.google.projectID }}
    role: roles/artifactregistry.reader
  providerConfigRef:
    name: {{ .Values.global.providerConfigRefName }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gar-token
  namespace: {{ .Values.global.google.createGARNamespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ $gsa }}@{{ .Values.global.google.projectID }}.iam.gserviceaccount.com
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: GCRAccessToken
metadata:
  name: gar-token
  namespace: {{ .Values.global.google.createGARNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  projectID: {{ .Values.global.google.projectID }}
  auth:
    workloadIdentity:
      clusterLocation: {{ .Values.global.google.region }}
      clusterName: {{ .Values.global.google.cluster.name }}
      clusterProjectID: {{ .Values.global.google.projectID }}
      serviceAccountRef:
        name: gar-token
---

  {{- range .Values.global.google.createGARProjects }}

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "repo-{{ .projectID }}-{{ .projectRegion }}"
  namespace: {{ $.Values.global.google.createGARNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 30m
  target:
    name: "repo-{{ .projectID }}-{{ .projectRegion }}"
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        name: "repo-{{ .projectID }}-{{ .projectRegion }}"
        type: helm
        enableOCI: "true"
        url: {{ .projectRegion }}-docker.pkg.dev/{{ .projectID }}
        password: "{{`{{ .password }}`}}"
        username: "{{`{{ .username }}`}}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GCRAccessToken
          name: gar-token
---
{{- end }}
{{- end }}
