{{- if eq .Values.global.cloudProvider "aws" }}
apiVersion: sqs.aws.upbound.io/v1beta1
kind: Queue
metadata:
  name: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  forProvider:
    name: {{ .Release.Name }}
    region: {{ .Values.global.aws.region }}
    tags:
      created-by: "entigo-infralib"
    delaySeconds: 0
    messageRetentionSeconds: 7200
    maxMessageSize: 8192
    receiveWaitTimeSeconds: 20
    visibilityTimeoutSeconds: 60
    policy: |
      {
        "Version": "2012-10-17",
        "Id": "__default_policy_ID",
        "Statement": [
          {
            "Sid": "__owner_statement",
            "Effect": "Allow",
            "Principal": {
              "AWS": "arn:aws:iam::{{ .Values.global.aws.account }}:root"
            },
            "Action": "sqs:*",
            "Resource": "arn:aws:sqs:{{ .Values.global.aws.region }}:{{ .Values.global.aws.account }}:{{ .Release.Name }}"
          },
          {
            "Sid": "AllowEventsToPush",
            "Effect": "Allow",
            "Principal": {
              "Service": "events.amazonaws.com"
            },
            "Action": "sqs:SendMessage",
            "Resource": "arn:aws:sqs:{{ .Values.global.aws.region }}:{{ .Values.global.aws.account }}:{{ .Release.Name }}",
            "Condition": {
              "ArnEquals": {
                "aws:SourceArn": "arn:aws:events:{{ .Values.global.aws.region }}:{{ .Values.global.aws.account }}:rule/entigo-portal-agent"
              }
            }
          }
        ]
      }
  providerConfigRef:
    name: {{ .Values.global.providerConfigRefName }}
{{- end }}
