promtail:
  config:
    clients:
      - url: http://{{ .tmodule.loki }}-gateway.{{ .tmodule.loki }}/loki/api/v1/push
  priorityClassName: "{{ .module.name }}"
  image:
    registry: '{{ .toptout.ecr-proxy.hub_registry | .toptout.gar-proxy.hub_registry | "docker.io" }}'
