apiVersion: v2
name: istio-base
description: istio-base
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: base
    version: 1.25.2
    repository: https://istio-release.storage.googleapis.com/charts
