metadata:
  annotations:
    infralib.entigo.io/sync-wave: "101"
spec:
  ignoreDifferences:
    - group: argoproj.io
      kind: AppProject
      jqPathExpressions:
        - '.spec.roles[]?.jwtTokens'
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: restricted
        pod-security.kubernetes.io/warn: restricted
        tenancy.entigo.com/zone: infralib
