apiVersion: v2
name: platform-apis
description: Platform APIs
version: v0.2.66
appVersion: "v0.2.66"
dependencies:
  - name: platform-apis
    version: v0.2.66
    repository: oci://ghcr.io/entigolabs
