apiVersion: v2
name: platform-apis
description: Platform APIs
version: v0.2.47
appVersion: "v0.2.47"
dependencies:
  - name: platform-apis
    version: v0.2.47
    repository: oci://ghcr.io/entigolabs
