apiVersion: apiextensions.crossplane.io/v1alpha1
kind: ManagedResourceActivationPolicy
metadata:
  name: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  activate:
  - 'topics.topic.kafka.crossplane.io'
  - 'accesscontrollists.acl.kafka.crossplane.io'
  - 'clusterproviderconfigusages.kafka.m.crossplane.io'
