{{- if eq .Values.global.cloudProvider "aws" }}
apiVersion: apiextensions.crossplane.io/v1alpha1
kind: ManagedResourceActivationPolicy
metadata:
  name: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: '-3'
spec:
  activate:
  - 'policies.iam.aws.upbound.io'
  - 'rolepolicyattachments.iam.aws.upbound.io'
  - 'roles.iam.aws.upbound.io'
  - 'buckets.s3.aws.upbound.io'
  - 'bucketacls.s3.aws.upbound.io'
  - 'bucketownershipcontrols.s3.aws.upbound.io'
  - 'bucketpublicaccessblocks.s3.aws.upbound.io'
  - 'bucketaccelerateconfigurations.s3.aws.upbound.io'
  - 'bucketversionings.s3.aws.upbound.io'
  - 'bucketserversideencryptionconfigurations.s3.aws.upbound.io'
  - 'bucketlifecycleconfigurations.s3.aws.upbound.io'
{{- end }}
