{{- if eq .Values.global.cloudProvider "aws" }}
apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: mimir-gateway
  namespace: {{ .Release.Namespace }}
spec:
  targetReference:
    name: mimir-gateway
  defaultConfiguration:
    # Replaces alb.ingress.kubernetes.io/target-type: ip
    targetType: ip
    healthCheckConfig:
      # Replaces healthcheck-path and success-codes annotations
      healthCheckPath: /ready
      matcher:
        httpCode: "200-499"
{{- end }}
