{{- if eq .Values.global.cloudProvider "aws" }}

apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  name: {{ .Release.Name }}
  annotations:
    crossplane.io/external-name: "{{ .Release.Name }}"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: '-2'
spec:
  forProvider:
    tags:
      created-by: "entigo-infralib"
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "AllowReadingMetricsFromCloudWatch",
            "Effect": "Allow",
            "Action": [
              "cloudwatch:DescribeAlarmsForMetric",
              "cloudwatch:DescribeAlarmHistory",
              "cloudwatch:DescribeAlarms",
              "cloudwatch:ListMetrics",
              "cloudwatch:GetMetricStatistics",
              "cloudwatch:GetMetricData",
              "cloudwatch:GetInsightRuleReport"
            ],
            "Resource": "*"
          },
          {
            "Sid": "AllowReadingLogsFromCloudWatch",
            "Effect": "Allow",
            "Action": [
              "logs:DescribeLogGroups",
              "logs:GetLogGroupFields",
              "logs:StartQuery",
              "logs:StopQuery",
              "logs:GetQueryResults",
              "logs:GetLogEvents"
            ],
            "Resource": "*"
          },
          {
            "Sid": "AllowReadingTagsInstancesRegionsFromEC2",
            "Effect": "Allow",
            "Action": ["ec2:DescribeTags", "ec2:DescribeInstances", "ec2:DescribeRegions"],
            "Resource": "*"
          },
          {
            "Sid": "AllowReadingResourcesForTags",
            "Effect": "Allow",
            "Action": "tag:GetResources",
            "Resource": "*"
          },
          {
            "Sid": "AllowReadingAcrossAccounts",
            "Effect": "Allow",
            "Action": [
              "oam:ListSinks",
              "oam:ListAttachedLinks"
            ],
            "Resource": "*"
          }
        ]
      }


  providerConfigRef:
    name: {{ .Values.global.providerConfigRefName }}

{{- end }}
