{{- if eq .Values.global.cloudProvider "aws" }}
apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  targetReference:
    name: grafana
  defaultConfiguration:
    healthCheckConfig:
      healthCheckPath: /api/health
{{- end }}
