global:
  cloudProvider: "aws"
  providerConfigRefName: "crossplane-aws"

  aws:
    account: ""
    clusterOIDC: ""
    region: ""
    ecrPolicy: ""

trivy-operator:
  serviceAccount:
    create: false
