apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: {{.Release.Name}}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  package: {{ .Values.global.registry }}/entigolabs/provider-kubernetes:v0.17.3
{{- if and (eq .Values.global.cloudProvider "aws") (ne .Values.global.registry "docker.io") }}
  packagePullSecrets: 
  - name: crossplane-ecr
{{- end }}
  runtimeConfigRef:
    name: {{.Release.Name}}
