apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: {{.Release.Name}}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  package: xpkg.upbound.io/upbound/provider-kubernetes:v0.17.3
  runtimeConfigRef:
    name: {{.Release.Name}}
