apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  name: {{ .Release.Name }}
  annotations:
    crossplane.io/external-name: "{{ .Release.Name }}"
    argocd.argoproj.io/sync-wave: '-2'
spec:
  forProvider:
    tags:
      created-by: "entigo-infralib"
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "autoscaling:DescribeAutoScalingGroups",
              "autoscaling:DescribeAutoScalingInstances",
              "autoscaling:DescribeLaunchConfigurations",
              "autoscaling:DescribeScalingActivities",
              "ec2:DescribeImages",
              "ec2:DescribeInstanceTypes",
              "ec2:DescribeLaunchTemplateVersions",
              "ec2:GetInstanceTypesFromInstanceRequirements",
              "eks:DescribeNodegroup"
            ],
            "Resource": ["*"]
          },
          {
            "Effect": "Allow",
            "Action": [
              "autoscaling:SetDesiredCapacity",
              "autoscaling:TerminateInstanceInAutoScalingGroup"
            ],
            "Resource": ["*"]
          }
        ]
      }
  providerConfigRef:
    name: {{ .Values.global.providerConfigRefName }}
