apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  name: {{ .Release.Name }} 
  annotations:
    crossplane.io/external-name: "{{ .Release.Name }}"
    argocd.argoproj.io/sync-wave: '-2'
spec:
  forProvider:
    tags:
      created-by: "entigo-infralib"
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
              "ecr:ListTagsForResource",
              "ecr:ListImages",
              "ecr:GetRepositoryPolicy",
              "ecr:GetLifecyclePolicyPreview",
              "ecr:GetLifecyclePolicy",
              "ecr:GetDownloadUrlForLayer",
              "ecr:GetAuthorizationToken",
              "ecr:DescribeRepositories",
              "ecr:DescribeImages",
              "ecr:DescribeImageScanFindings",
              "ecr:BatchGetImage",
              "ecr:BatchCheckLayerAvailability"
            ],
            "Resource": "*"
          }
        ]
      }

  providerConfigRef:
    name: {{ .Values.global.providerConfigRefName }}

