config: {}

resources:
  limits:
    cpu: 500m
    memory: 512Mi
    ephemeral-storage: 512Mi
  requests:
    cpu: 10m
    memory: 64Mi
    ephemeral-storage: 10Mi

image:
  repository: docker.io/entigolabs/vulnerability-agent
  tag: 5

tolerations:
  - key: "tools"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 90
        preference:
          matchExpressions:
            - key: tools
              operator: In
              values:
                - "true"
